In [ ]:
import numpy as np
import pandas as pd
import pprint
eps = np.finfo(float).eps
from numpy import log2 as log
import matplotlib.pyplot as plt 
import math
from collections import defaultdict

## Categorical Input Data

In [ ]:
n = int(input('Number of input features: '))
input_features = {}
for i in range(n):
  input_features[i] = input('Enter {}th feature: '.format(i+1)).split(',')
  print()
input_features

Number of input features: 4
Enter 1th feature: y,n,n,y,n,n,y,n,n,n

Enter 2th feature: s,m,s,m,d,m,d,s,m,s

Enter 3th feature: g,g,l,g,g,l,g,g,g,g

Enter 4th feature: n,n,n,n,y,n,n,y,n,y



{0: ['y', 'n', 'n', 'y', 'n', 'n', 'y', 'n', 'n', 'n'],
 1: ['s', 'm', 's', 'm', 'd', 'm', 'd', 's', 'm', 's'],
 2: ['g', 'g', 'l', 'g', 'g', 'l', 'g', 'g', 'g', 'g'],
 3: ['n', 'n', 'n', 'n', 'y', 'n', 'n', 'y', 'n', 'y']}

## Continuous Input Data

In [ ]:
n = int(input('Number of input features: '))
input_features = {}
for i in range(n):
  input_features[i] = list(map(float, input('Enter {}th feature: '.format(i+1)).split(',')))
  print()
input_features

Number of input features: 2
Enter 1th feature: 2,3,5,7,8,9

Enter 2th feature: 7,6,5,4,3,5



{0: [2.0, 3.0, 5.0, 7.0, 8.0, 9.0], 1: [7.0, 6.0, 5.0, 4.0, 3.0, 5.0]}

## Mixed Data

In [ ]:
n = int(input('Number of input features: '))
input_features = {}
for i in range(n):
  feature_type = input("Enter type of data [int/str/float]: ")
  if feature_type == 'float':
    input_features[i] = list(map(float, input('Enter {}th feature: '.format(i+1)).split(',')))
  elif feature_type == 'int':
    input_features[i] = list(map(int, input('Enter {}th feature: '.format(i+1)).split(',')))
  else:
    input_features[i] = input('Enter {}th feature: '.format(i+1)).split(',')
  print()
input_features

In [ ]:
feature_names = input("Enter feature names: ").split(',')

Enter feature names: x1,x2


In [ ]:
for j, i in enumerate(feature_names):
  input_features[i] = input_features[j]
  del input_features[j]

In [ ]:
data = pd.DataFrame(input_features)

In [ ]:
data

x1   x2
0  2.0  7.0
1  3.0  6.0
2  5.0  5.0
3  7.0  4.0
4  8.0  3.0
5  9.0  5.0

## ID3

In [ ]:
# Entropy of dataset
entropy_node = 0  
values = data.label.unique() 
for value in values:
  fraction = data.label.value_counts()[value]/len(data.label)  
  entropy_node += -fraction*np.log2(fraction)
print("Entropy = SIGMA ( -pi * log2(pi) )")
entropy_node

Entropy = SIGMA ( -pi * log2(pi) )


0.9402859586706309

In [ ]:
def ent(df,attribute):
  target_variables = df.label.unique()
  variables = df[attribute].unique()
  entropy_attribute = 0
  for variable in variables:
    entropy_each_feature = 0
    for target_variable in target_variables:
      print()
      num = len(df[attribute][df[attribute]==variable][df.label ==target_variable]) 
      den = len(df[attribute][df[attribute]==variable])
      print("p_{}_{} = {}/{}".format(variable, target_variable, num, den), end=' ')
      fraction = num/(den) 
      if fraction == 0:
        print(0)
        continue
      entropy_each_feature += -fraction*log(fraction) 
      print(" + ( -pi * log2(pi) ) = {}".format(entropy_each_feature))
    fraction2 = den/len(df)
    entropy_attribute += -fraction2*entropy_each_feature  
  return(abs(entropy_attribute))
entropies = {}
for feature in feature_names[:-1]:
  entropies[feature] = ent(data, feature)
print()
entropies


p_overcast_yes = 4/4  + ( -pi * log2(pi) ) = 0.0

p_overcast_no = 0/4 0

p_rainy_yes = 3/5  + ( -pi * log2(pi) ) = 0.44217935649972373

p_rainy_no = 2/5  + ( -pi * log2(pi) ) = 0.9709505944546686

p_sunny_yes = 2/5  + ( -pi * log2(pi) ) = 0.5287712379549449

p_sunny_no = 3/5  + ( -pi * log2(pi) ) = 0.9709505944546686

p_hot_yes = 2/4  + ( -pi * log2(pi) ) = 0.5

p_hot_no = 2/4  + ( -pi * log2(pi) ) = 1.0

p_cool_yes = 3/4  + ( -pi * log2(pi) ) = 0.31127812445913283

p_cool_no = 1/4  + ( -pi * log2(pi) ) = 0.8112781244591328

p_mild_yes = 4/6  + ( -pi * log2(pi) ) = 0.38997500048077083

p_mild_no = 2/6  + ( -pi * log2(pi) ) = 0.9182958340544896

p_high_yes = 3/7  + ( -pi * log2(pi) ) = 0.5238824662870492

p_high_no = 4/7  + ( -pi * log2(pi) ) = 0.9852281360342515

p_normal_yes = 6/7  + ( -pi * log2(pi) ) = 0.19062207543124116

p_normal_no = 1/7  + ( -pi * log2(pi) ) = 0.5916727785823275

p_FALSE_yes = 6/8  + ( -pi * log2(pi) ) = 0.31127812445913283

p_FALSE_no = 2/8  + ( -pi * log2(pi)

{'humidity': 0.7884504573082896,
 'outlook': 0.6935361388961918,
 'temp': 0.9110633930116763,
 'windy': 0.8921589282623617}

In [ ]:
def ig(e_dataset,e_attr):
  return(e_dataset-e_attr)
info_gain = {k:ig(entropy_node,entropies[k]) for k in entropies}
info_gain

{'humidity': 0.15183550136234136,
 'outlook': 0.2467498197744391,
 'temp': 0.029222565658954647,
 'windy': 0.04812703040826927}

In [ ]:
#@title ID3 Decision Tree
def find_entropy(df):
    Class = df.keys()[-1]   #To make the code generic, changing target variable class name
    entropy = 0
    values = df[Class].unique()
    for value in values:
        fraction = df[Class].value_counts()[value]/len(df[Class])
        entropy += -fraction*np.log2(fraction)
    return entropy
  
  
def find_entropy_attribute(df,attribute):
  Class = df.keys()[-1]   #To make the code generic, changing target variable class name
  target_variables = df[Class].unique()  #This gives all 'Yes' and 'No'
  variables = df[attribute].unique()    #This gives different features in that attribute (like 'Hot','Cold' in Temperature)
  entropy2 = 0
  for variable in variables:
      entropy = 0
      for target_variable in target_variables:
          num = len(df[attribute][df[attribute]==variable][df[Class] ==target_variable])
          den = len(df[attribute][df[attribute]==variable])
          fraction = num/(den+eps)
          entropy += -fraction*log(fraction+eps)
      fraction2 = den/len(df)
      entropy2 += -fraction2*entropy
  return abs(entropy2)


def find_winner(df):
    Entropy_att = []
    IG = []
    for key in df.keys()[:-1]:
#         Entropy_att.append(find_entropy_attribute(df,key))
        IG.append(find_entropy(df)-find_entropy_attribute(df,key))
    return df.keys()[:-1][np.argmax(IG)]
  
  
def get_subtable(df, node,value):
  return df[df[node] == value].reset_index(drop=True)


def buildTree(df,tree=None): 
    Class = df.keys()[-1]   #To make the code generic, changing target variable class name
    
    #Here we build our decision tree

    #Get attribute with maximum information gain
    node = find_winner(df)
    
    #Get distinct value of that attribute e.g Salary is node and Low,Med and High are values
    attValue = np.unique(df[node])
    
    #Create an empty dictionary to create tree    
    if tree is None:                    
        tree={}
        tree[node] = {}
    
   #We make loop to construct a tree by calling this function recursively. 
    #In this we check if the subset is pure and stops if it is pure. 

    for value in attValue:
        
        subtable = get_subtable(df,node,value)
        clValue,counts = np.unique(subtable['label'],return_counts=True)                        
        
        if len(counts)==1:#Checking purity of subset
            tree[node][value] = clValue[0]                                                    
        else:        
            tree[node][value] = buildTree(subtable) #Calling the function recursively 
                   
    return tree

In [ ]:
t = buildTree(data)
pprint.pprint(t)

{'outlook': {'overcast': 'yes',
             'rainy': {'windy': {'FALSE': 'yes', 'TRUE': 'no'}},
             'sunny': {'humidity': {'high': 'no', 'normal': 'yes'}}}}


In [ ]:
#@title Bayes Classifier
def accuracy_score(y_true, y_pred):
  return float(sum(y_pred == y_true))/float(len(y_true)) * 100 
def pre_processing(df):
  X = df.drop([df.columns[-1]], axis = 1)
  y = df[df.columns[-1]]
  return X, y
class  NaiveBayes:
	def __init__(self):
		self.features = list
		self.likelihoods = {}
		self.class_priors = {}
		self.pred_priors = {}
		self.X_train = np.array
		self.y_train = np.array
		self.train_size = int
		self.num_feats = int
	def fit(self, X, y):
		self.features = list(X.columns)
		self.X_train = X
		self.y_train = y
		self.train_size = X.shape[0]
		self.num_feats = X.shape[1]
		for feature in self.features:
			self.likelihoods[feature] = {}
			self.pred_priors[feature] = {}
			for feat_val in np.unique(self.X_train[feature]):
				self.pred_priors[feature].update({feat_val: 0})
				for outcome in np.unique(self.y_train):
					self.likelihoods[feature].update({feat_val+'_'+outcome:0})
					self.class_priors.update({outcome: 0})
		print("\nCLASS PRIORS");self._calc_class_prior();print(self.class_priors)
		print("\n\nLIKELIHOODS");self._calc_likelihoods();print(self.likelihoods)
		print("\n\nPREDICTOR PRIORS");self._calc_predictor_prior();print(self.pred_priors)
	def _calc_class_prior(self):
		for outcome in np.unique(self.y_train):
			outcome_count = sum(self.y_train == outcome)
			self.class_priors[outcome] = outcome_count / self.train_size;print(outcome, outcome_count, self.train_size)
	def _calc_likelihoods(self):
		for feature in self.features:
			for outcome in np.unique(self.y_train):
				outcome_count = sum(self.y_train == outcome)
				feat_likelihood = self.X_train[feature][self.y_train[self.y_train == outcome].index.values.tolist()].value_counts().to_dict()
				for feat_val, count in feat_likelihood.items():
					self.likelihoods[feature][feat_val + '_' + outcome] = count/outcome_count;print(outcome, outcome_count, feat_likelihood, feat_val, count, count/outcome_count)
	def _calc_predictor_prior(self):
		for feature in self.features:
			feat_vals = self.X_train[feature].value_counts().to_dict()
			for feat_val, count in feat_vals.items():
				self.pred_priors[feature][feat_val] = count/self.train_size;print(feature, feat_vals, feat_val, count, count/self.train_size)
	def predict(self, X):
		results = []
		X = np.array(X)
		for query in X:
			probs_outcome = {}
			for outcome in np.unique(self.y_train):
				prior = self.class_priors[outcome]
				likelihood = 1
				evidence = 1
				for feat, feat_val in zip(self.features, query):
					likelihood *= self.likelihoods[feat][feat_val + '_' + outcome]
					evidence *= self.pred_priors[feat][feat_val]
				posterior = (likelihood * prior) / (evidence)
				probs_outcome[outcome] = posterior
			result = max(probs_outcome, key = lambda x: probs_outcome[x])
			results.append(result)
		print("\n",probs_outcome);return np.array(results)

In [ ]:
"""
		Bayes Theorem:
										            Likelihood * Class prior probability
				Posterior Probability = -------------------------------------
											            Predictor prior probability
				
							  			      P(x|c) * p(c)
							   P(c|x) = ------------------ 
											          P(x)
	"""


'\n\t\tBayes Theorem:\n\t\t\t\t\t\t\t\t\t\t            Likelihood * Class prior probability\n\t\t\t\tPosterior Probability = -------------------------------------\n\t\t\t\t\t\t\t\t\t\t\t            Predictor prior probability\n\t\t\t\t\n\t\t\t\t\t\t\t  \t\t\t      P(x|c) * p(c)\n\t\t\t\t\t\t\t   P(c|x) = ------------------ \n\t\t\t\t\t\t\t\t\t\t\t          P(x)\n\t'

In [ ]:
X,y  = pre_processing(data)
nb_clf = NaiveBayes()
nb_clf.fit(X, y)
#Query 1:
query = np.array([['y','m','l']])
print("\nQuery 1:- {} ---> {}".format(query, nb_clf.predict(query)))


CLASS PRIORS
n 7 10
y 3 10
{'n': 0.7, 'y': 0.3}


LIKELIHOODS
n 7 {'n': 4, 'y': 3} n 4 0.5714285714285714
n 7 {'n': 4, 'y': 3} y 3 0.42857142857142855
y 3 {'n': 3} n 3 1.0
n 7 {'m': 4, 's': 2, 'd': 1} m 4 0.5714285714285714
n 7 {'m': 4, 's': 2, 'd': 1} s 2 0.2857142857142857
n 7 {'m': 4, 's': 2, 'd': 1} d 1 0.14285714285714285
y 3 {'s': 2, 'd': 1} s 2 0.6666666666666666
y 3 {'s': 2, 'd': 1} d 1 0.3333333333333333
n 7 {'g': 5, 'l': 2} g 5 0.7142857142857143
n 7 {'g': 5, 'l': 2} l 2 0.2857142857142857
y 3 {'g': 3} g 3 1.0
{'refund': {'n_n': 0.5714285714285714, 'n_y': 1.0, 'y_n': 0.42857142857142855, 'y_y': 0}, 'marital': {'d_n': 0.14285714285714285, 'd_y': 0.3333333333333333, 'm_n': 0.5714285714285714, 'm_y': 0, 's_n': 0.2857142857142857, 's_y': 0.6666666666666666}, 'taxable': {'g_n': 0.7142857142857143, 'g_y': 1.0, 'l_n': 0.2857142857142857, 'l_y': 0}}


PREDICTOR PRIORS
refund {'n': 7, 'y': 3} n 7 0.7
refund {'n': 7, 'y': 3} y 3 0.3
marital {'m': 4, 's': 4, 'd': 2} m 4 0.4
marital {'m

In [ ]:
#@title KNN
def EuclideanDistance(row, point):
  distance = 0.0
  for i in range(len(point)):
    distance += (row[i] - point[i]) ** 2
  return distance**0.5

def find_k_minimums(k, dataset):
  distances = []
  for index, row in dataset.iterrows():
    distances.append(row['distance'])
  min_indices = []
  while len(min_indices)<k:
    minDist = float('inf')
    minIndex = -1
    for i in range(len(distances)):
      if i not in min_indices and distances[i]<minDist:
        minDist = distances[i]
        minIndex = i
    min_indices.append(minIndex)
  return min_indices

def run_KNN(k, data, point):
  distanceList = []
  for rowIndex in range(len(data)):
    rowItems = []
    # print(row)
    # for each in feature_names:
    #   rowItems.append(row.each)
    distanceList.append(EuclideanDistance(list(data.iloc[rowIndex]), point))
  data['distance'] = distanceList
  minIndices = find_k_minimums(k, data)
  print(data)
  print("\nMin Indices: {}".format(minIndices))
  print("\nMin Tuples: \n{}".format(data.iloc[minIndices]))

In [ ]:
run_KNN(3,data,(15.2,33.1))

       x1    x2  label   distance
0   11.35  23.0    0.0  10.808908
1   11.59  22.3    0.0  11.387366
2   12.19  24.5    0.0   9.111537
3   13.23  26.4    0.0   6.983617
4   13.51  30.2    0.0   3.356501
5   13.68  32.0    0.0   1.876273
6   14.78  33.1    0.0   0.420000
7   15.11  33.0    0.0   0.134536
8   15.55  25.2    0.0   7.907749
9   11.85  39.9    1.0   7.580402
10  12.09  39.5    1.0   7.115624
11  12.69  37.8    1.0   5.328236
12  13.73  38.2    1.0   5.307627
13  14.01  37.8    1.0   4.848309
14  14.18  36.5    1.0   3.549704
15  15.28  36.0    1.0   2.901103
16  15.61  37.1    1.0   4.020958
17  16.05  33.1    1.0   0.850000

Min Indices: [7, 6, 17]

Min Tuples: 
       x1    x2  label  distance
7   15.11  33.0    0.0  0.134536
6   14.78  33.1    0.0  0.420000
17  16.05  33.1    1.0  0.850000


In [ ]:
#@title Confusion Matrix Evaluation

def input_confusion_matrix(n=2):
  matrix = []
  for i in range(n):
    row = list(map(int, input("Row{}: ".format(i+1)).split(',')))
    matrix.append(row)
  return matrix

def get_performance_measures():
  matrix = input_confusion_matrix()
  TP = matrix[0][0]
  FN = matrix[0][1]
  FP = matrix[1][0]
  TN = matrix[1][1]
  TotN = TP + TN + FP + FN
  print("True Positive: {}".format(TP))
  print("False Negative: {}".format(FN))
  print("False Positive: {}".format(FP))
  print("True Negative: {}".format(TN))
  print("Total Predictions: {}".format(TotN))
  print("\nPredictive Accuracy")
  print("Predictive Accuracy = (TP + TN) / (TotN) = ({} + {}) / {} = {}".format(TP, TN, TotN, (TP + TN)/TotN))
  print("\nError Rate")
  print("Error Rate = 1 - ((TP + TN) / (TotN)) = 1 - (({} + {}) / {}) = {}".format(TP, TN, TotN, 1-(TP + TN)/TotN))
  print("\nTrue Positive Rate / Recall / Sensitivity / Hit Rate")
  print("TPR = TP / (TP + FN) = {} / ({} + {}) = {}".format(TP, TP, FN, TP / (TP + FN)))
  print("\nFalse Positive Rate / False Alarm Rate")
  print("FPR = FP / (FP + TN) = {} / ({} + {}) = {}".format(FP, FP, TN, FP / (FP + TN)))
  print("\nFalse Negative Rate")
  print("FNR = FN / (TP + FN) = {} / ({} + {}) = {}".format(FN, TP, FN, FN / (TP + FN)))
  print("\nTrue Negative Rate / Specificity")
  print("TNR = TN / (FP + TN) = {} / ({} + {}) = {}".format(TN, FP, TN, TN / (FP + TN)))
  print("\nPositive Predictive Value / Precision")
  print("PPV = TP / (TP + FP) = {} / ({} + {}) = {}".format(TP, TP, FP, TP / (TP + FP)))
  print("\nF1 Score")
  print("F1 = 2TP / (2TP + FP + FN) = 2*{} / (2*{} + {} + {}) = {}".format(TP, TP, FP, FN,(2 * TP / (2 * TP + FP + FN))))



In [ ]:
get_performance_measures()

Row1: 52,18
Row2: 21,123
True Positive: 52
False Negative: 18
False Positive: 21
True Negative: 123
Total Predictions: 214

Predictive Accuracy
Predictive Accuracy = (TP + TN) / (TotN) = (52 + 123) / 214 = 0.8177570093457944

Error Rate
Error Rate = 1 - ((TP + TN) / (TotN)) = 1 - ((52 + 123) / 214) = 0.18224299065420557

True Positive Rate / Recall / Sensitivity / Hit Rate
TPR = TP / (TP + FN) = 52 / (52 + 18) = 0.7428571428571429

False Positive Rate / False Alarm Rate
FPR = FP / (FP + TN) = 21 / (21 + 123) = 0.14583333333333334

False Negative Rate
FNR = FN / (TP + FN) = 18 / (52 + 18) = 0.2571428571428571

True Negative Rate / Specificity
TNR = TN / (FP + TN) = 123 / (21 + 123) = 0.8541666666666666

Positive Predictive Value / Precision
PPV = TP / (TP + FP) = 52 / (52 + 21) = 0.7123287671232876

F1 Score
F1 = 2TP / (2TP + FP + FN) = 2*52 / (2*52 + 21 + 18) = 0.7272727272727273


# Linear Regression, Logistic Regression

In [ ]:
x1 = np.array([60,47,65,57,42,33,47,33,45,53])
x2 = np.array([49,45,61,47,29,17,23,14,33,41])
x3 = np.array([75,75,81,68,64,60,44,48,69,68])
x4 = np.array([4,1,6,4,9,5,9,6,11,2])
# x5 = np.array([])
# x6 = np.array([])
# x7 = np.array([])
y = np.array([0.46,0.16,0.1,0.01,0.06,0.05,0.02,0.05,0.02,0.15])

x1bar = np.mean(x1)
x2bar = np.mean(x2)
x3bar = np.mean(x3)
x4bar = np.mean(x4)
# x5bar = np.sum(x5)/len(x5)
# x6bar = np.sum(x6)/len(x6)
# x7bar = np.sum(x7)/len(x7)
ybar = np.mean(y)

x1_x1bar = x1-x1bar
x2_x2bar = x2-x2bar
x3_x3bar = x3-x3bar
x4_x4bar = x4-x4bar
# x5_x5bar = x5-x5bar
# x6_x6bar = x6-x6bar
# x7_x7bar = x7-x7bar
y_ybar = y-ybar

x1_x1bar_y_ybar = x1_x1bar*y_ybar
x2_x2bar_y_ybar = x2_x2bar*y_ybar
x3_x3bar_y_ybar = x3_x3bar*y_ybar
x4_x4bar_y_ybar = x4_x4bar*y_ybar
# x5_x5bar_y_ybar = x5_x5bar*y_ybar
# x6_x6bar_y_ybar = x6_x6bar*y_ybar
# x7_x7bar_y_ybar = x7_x7bar*y_ybar

x1_x1bar2 = x1_x1bar**2
x2_x2bar2 = x2_x2bar**2
x3_x3bar2 = x3_x3bar**2
x4_x4bar2 = x4_x4bar**2
# x5_x5bar2 = x5_x5bar**2
# x6_x6bar2 = x6_x6bar**2
# x7_x7bar2 = x7_x7bar**2

w1 = np.sum(x1_x1bar_y_ybar) / np.sum(x1_x1bar2)
w2 = np.sum(x2_x2bar_y_ybar) / np.sum(x2_x2bar2)
w3 = np.sum(x3_x3bar_y_ybar) / np.sum(x3_x3bar2)
w4 = np.sum(x4_x4bar_y_ybar) / np.sum(x4_x4bar2)
# w5 = np.sum(x5_x5bar_y_ybar) / np.sum(x5_x5bar2)
# w6 = np.sum(x6_x6bar_y_ybar) / np.sum(x6_x6bar2)
# w7 = np.sum(x7_x7bar_y_ybar) / np.sum(x7_x7bar2)

w0 = ybar - w1*x1bar - w2*x2bar - w3*x3bar - w4*x4bar # -w5*x5bar # -w6*x6bar # - w7*x7bar

In [ ]:
columns = np.array(["x1", "x2", "x3", "x4", "y", "x1-x1bar", "x2-x2bar", "x3-x3bar", "x4-x4bar", "y-ybar", "x1-x1bar * y-ybar", "x2-x2bar * y-ybar", "x3-x3bar * y-ybar", "x4-x4bar * y-ybar", "x1-x1bar^2", "x2-x2bar^2", "x3-x3bar^2", "x4-x4bar^2"])
dataset = np.array([x1, x2, x3, x4, y, x1_x1bar, x2_x2bar, x3_x3bar, x4_x4bar, y_ybar, x1_x1bar_y_ybar, x2_x2bar_y_ybar, x3_x3bar_y_ybar, x4_x4bar_y_ybar, x1_x1bar2, x2_x2bar2, x3_x3bar2, x4_x4bar2])
regression = pd.DataFrame(data=dataset.T, columns=columns)
regression

x1    x2    x3    x4  ...  x1-x1bar^2  x2-x2bar^2  x3-x3bar^2  x4-x4bar^2
0  60.0  49.0  75.0   4.0  ...      139.24      171.61       96.04        2.89
1  47.0  45.0  75.0   1.0  ...        1.44       82.81       96.04       22.09
2  65.0  61.0  81.0   6.0  ...      282.24      630.01      249.64        0.09
3  57.0  47.0  68.0   4.0  ...       77.44      123.21        7.84        2.89
4  42.0  29.0  64.0   9.0  ...       38.44       47.61        1.44       10.89
5  33.0  17.0  60.0   5.0  ...      231.04      357.21       27.04        0.49
6  47.0  23.0  44.0   9.0  ...        1.44      166.41      449.44       10.89
7  33.0  14.0  48.0   6.0  ...      231.04      479.61      295.84        0.09
8  45.0  33.0  69.0  11.0  ...       10.24        8.41       14.44       28.09
9  53.0  41.0  68.0   2.0  ...       23.04       26.01        7.84       13.69

[10 rows x 18 columns]

In [ ]:
print("w0 = {}".format(w0))
print("w1 = {}".format(w1))
print("w2 = {}".format(w2))
print("w3 = {}".format(w3))
print("w4 = {}".format(w4))

w0 = -0.5350170731358121
w1 = 0.005546543066821167
w2 = 0.003869272301591094
w3 = 0.005269749518304431
w4 = -0.018740499457111832


In [ ]:
predx1 = 44
predx2 = 33
predx3 = 63
predx4 = 8
predy = w0 + w1*predx1 + w2*predx2 + w3*predx3 + w4*predx4
predy

0.018787031753109806

In [ ]:
x1 = np.array([28,39,29,33,15])
# x2 = np.array([49,45,61,47,29,17,23,14,33,41])
# x3 = np.array([75,75,81,68,64,60,44,48,69,68])
# x4 = np.array([4,1,6,4,9,5,9,6,11,2])
# x5 = np.array([])
# x6 = np.array([])
# x7 = np.array([])
y = np.array([1,1,0,1,0])

x1bar = np.mean(x1)
# x2bar = np.mean(x2)
# x3bar = np.mean(x3)
# x4bar = np.mean(x4)
# x5bar = np.sum(x5)/len(x5)
# x6bar = np.sum(x6)/len(x6)
# x7bar = np.sum(x7)/len(x7)
ybar = np.mean(y)

x1_x1bar = x1-x1bar
# x2_x2bar = x2-x2bar
# x3_x3bar = x3-x3bar
# x4_x4bar = x4-x4bar
# x5_x5bar = x5-x5bar
# x6_x6bar = x6-x6bar
# x7_x7bar = x7-x7bar
y_ybar = y-ybar

x1_x1bar_y_ybar = x1_x1bar*y_ybar
# x2_x2bar_y_ybar = x2_x2bar*y_ybar
# x3_x3bar_y_ybar = x3_x3bar*y_ybar
# x4_x4bar_y_ybar = x4_x4bar*y_ybar
# x5_x5bar_y_ybar = x5_x5bar*y_ybar
# x6_x6bar_y_ybar = x6_x6bar*y_ybar
# x7_x7bar_y_ybar = x7_x7bar*y_ybar

x1_x1bar2 = x1_x1bar**2
# x2_x2bar2 = x2_x2bar**2
# x3_x3bar2 = x3_x3bar**2
# x4_x4bar2 = x4_x4bar**2
# x5_x5bar2 = x5_x5bar**2
# x6_x6bar2 = x6_x6bar**2
# x7_x7bar2 = x7_x7bar**2

w1 = np.sum(x1_x1bar_y_ybar) / np.sum(x1_x1bar2)
# w2 = np.sum(x2_x2bar_y_ybar) / np.sum(x2_x2bar2)
# w3 = np.sum(x3_x3bar_y_ybar) / np.sum(x3_x3bar2)
# w4 = np.sum(x4_x4bar_y_ybar) / np.sum(x4_x4bar2)
# w5 = np.sum(x5_x5bar_y_ybar) / np.sum(x5_x5bar2)
# w6 = np.sum(x6_x6bar_y_ybar) / np.sum(x6_x6bar2)
# w7 = np.sum(x7_x7bar_y_ybar) / np.sum(x7_x7bar2)

w0 = ybar - w1*x1bar #- w2*x2bar - w3*x3bar - w4*x4bar # -w5*x5bar # -w6*x6bar # - w7*x7bar

In [ ]:
predy = w0 + w1*40

In [ ]:
# Logistic ==> Linear + sigmoid
predy_logistic = 1. / (1. + np.exp(-predy))
predy_logistic

0.7478081816843715

# BackPropagation

In [ ]:
def sigmoid(z):
  return 1. / (1. + np.exp(-z))

In [ ]:
def bipolar(z):
  return (1. - np.exp(-z)) / (1. + np.exp(-z))

In [ ]:
def f_dash(z):
  return z * (1 - z)

In [ ]:
def f_dash_bipolar(z):
  return 0.5 * (1+z) * (1-z)

In [ ]:
inp=2
hidden=2
output=1
x_in = np.array(list(map(float, input('Enter {} input signals: '.format(inp)).split(','))))
w_hidden = []
for i in range(inp):
  w_hidden.append(np.array(list(map(float, input('Enter {} weights for the {}th input signals: '.format(hidden, i+1)).split(',')))))
w_hidden = np.array(w_hidden)
w_output = []
for i in range(hidden):
  w_output.append(np.array(list(map(float, input('Enter {} weights for the {}th hidden signals: '.format(output, i+1)).split(',')))))
w_output = np.array(w_output)
b_hidden = int(input("Enter Hidden Layer Bias: "))
b_output = int(input("Enter Output Layer Bias: "))
weights_bias_hidden = np.array(list(map(float,input("Enter hidden layer bias weights: ").split(','))))
weights_bias_output = np.array(list(map(float,input("Enter output layer bias weights: ").split(','))))
target = np.array(list(map(float, input("Enter {} target signal: ".format(output)).split(','))))
alpha = float(input("Enter learning rate: "))
print(x_in)
print(w_hidden)
print(w_output)
print(b_hidden)
print(b_output)
print(weights_bias_hidden)
print(weights_bias_output)

Enter 2 input signals: 0,1
Enter 2 weights for the 1th input signals: 0.6,-0.3
Enter 2 weights for the 2th input signals: -0.1,0.4
Enter 1 weights for the 1th hidden signals: 0.4
Enter 1 weights for the 2th hidden signals: 0.1
Enter Hidden Layer Bias: 1
Enter Output Layer Bias: 1
Enter hidden layer bias weights: 0.3,0.5
Enter output layer bias weights: -0.2
Enter 1 target signal: 1
Enter learning rate: 0.25
[0. 1.]
[[ 0.6 -0.3]
 [-0.1  0.4]]
[[0.4]
 [0.1]]
1
1
[0.3 0.5]
[-0.2]


In [ ]:
# z1_in z2_in
z_in = np.zeros((1,hidden))
for i in range(hidden):
  for j in range(inp):
    z_in[0][i] += x_in[j] * w_hidden[j][i]
  z_in[0][i] += b_hidden * weights_bias_hidden[i]
print(z_in)

[[0.2 0.9]]


In [ ]:
# z1  z2
z_out = sigmoid(z_in)
z_out

array([[0.549834 , 0.7109495]])

In [ ]:
# y_in
y_in = np.zeros((1,output))
for i in range(output):
  for j in range(hidden):
    y_in[0][i] += z_out[0][j] * w_output[j][i]
  y_in[0][i] += b_output * weights_bias_output[i]
print(y_in)

[[0.09102855]]


In [ ]:
# y
y_out = sigmoid(y_in)
y_out

array([[0.52274144]])

In [ ]:
# delta 1
delta_k = (target - y_out) * f_dash(y_out)
delta_k

array([[0.11906782]])

In [ ]:
# delta w1, delta w2
delta_w_output = alpha * delta_k * z_out
delta_w_output

array([[0.01636688, 0.0211628 ]])

In [ ]:
# delta w0
delta_w_bias_output = alpha * delta_k
delta_w_bias_output

array([[0.02976695]])

In [ ]:
# new w1
# new w2
new_w_output = w_output + delta_w_output.T
new_w_output

array([[0.41636688],
       [0.1211628 ]])

In [ ]:
# new w0
new_bias_output = b_output*weights_bias_output + delta_w_bias_output.T
new_bias_output

array([[-0.17023305]])

In [ ]:
delta_k*w_output, f_dash_bipolar(z_out)

(array([[0.04762713],
        [0.01190678]]), array([[0.34884129, 0.2472754 ]]))

In [ ]:
# Error propagation from hidden layer
# delta 1
# delta 2
new_delta_hidden = delta_k * w_output * f_dash(z_out).T
new_delta_hidden

array([[0.0117885 ],
       [0.00244685]])

In [ ]:
# delta v11   #   delta v21
# delta v12   #   delta v22
delta_w_hidden = alpha * x_in * new_delta_hidden
delta_w_hidden

array([[0.        , 0.00294713],
       [0.        , 0.00061171]])

In [ ]:
# delta v01
# delta v02
delta_w_bias_hidden = alpha * new_delta_hidden
delta_w_bias_hidden

array([[0.00294713],
       [0.00061171]])

In [ ]:
# new v11   new v12
# new v21   new v22
new_w_hidden = w_hidden + delta_w_hidden.T
new_w_hidden

array([[ 0.6       , -0.3       ],
       [-0.09705287,  0.40061171]])

In [ ]:
# new v01   new v02
new_bias_hidden = b_hidden*weights_bias_hidden + delta_w_bias_hidden.T
new_bias_hidden

array([[0.30294713, 0.50061171]])

# K-Means

In [ ]:
def EuclideanDistance(row, point):
  distance = 0.0
  for i in range(len(point)):
    distance += (row[i] - point[i]) ** 2
  return distance**0.5

def find_mean(list_of_tuples):
  sums = [0 for i in range(len(list_of_tuples[0]))]
  for i in list_of_tuples:
    for j in range(len(i)):
      sums[j] += i[j]
  return list(np.array(sums)/len(list_of_tuples))


cluster_indices = [1,3]
centroids = []
for index in cluster_indices:
  point = (data.iloc[index]['x1'], data.iloc[index]['x2'])
  centroids.append(point)
flag = True
newCentroids = centroids.copy()
while flag or tuple(sorted(centroids)) != tuple(sorted(newCentroids)):
  centroids = newCentroids.copy()
  flag = False
  newCentroids = []
  newData = data.copy()
  for j,centroid in enumerate(centroids):
    distanceList = []
    for rowIndex in range(len(data)):
      rowItems = []
      distanceList.append(EuclideanDistance(list(data.iloc[rowIndex]), centroid))
    newData[j] = distanceList
  print(newData)
  clusters = defaultdict(list)
  for rowIndex in range(len(data)):
    minIndex = 0
    minVal = newData.iloc[rowIndex][0]
    for i in range(1, len(centroids)):
      val = newData.iloc[rowIndex][i]
      if minVal>val:
        minVal = val
        minIndex = i
    clusters[minIndex].append((newData.iloc[rowIndex]['x1'], newData.iloc[rowIndex]['x2']))
  for cluster in clusters:
    newCentroids.append(tuple(find_mean(clusters[cluster])))
  print(newCentroids)
  print(clusters)
  # newCentroids = centroids

    x1   x2         0         1
0  2.0  7.0  1.414214  5.830952
1  3.0  6.0  0.000000  4.472136
2  5.0  5.0  2.236068  2.236068
3  7.0  4.0  4.472136  0.000000
4  8.0  3.0  5.830952  1.414214
5  9.0  5.0  6.082763  2.236068
[(3.3333333333333335, 6.0), (8.0, 4.0)]
defaultdict(<class 'list'>, {0: [(2.0, 7.0), (3.0, 6.0), (5.0, 5.0)], 1: [(7.0, 4.0), (8.0, 3.0), (9.0, 5.0)]})
    x1   x2         0         1
0  2.0  7.0  1.666667  6.708204
1  3.0  6.0  0.333333  5.385165
2  5.0  5.0  1.943651  3.162278
3  7.0  4.0  4.176655  1.000000
4  8.0  3.0  5.547772  1.000000
5  9.0  5.0  5.754226  1.414214
[(3.3333333333333335, 6.0), (8.0, 4.0)]
defaultdict(<class 'list'>, {0: [(2.0, 7.0), (3.0, 6.0), (5.0, 5.0)], 1: [(7.0, 4.0), (8.0, 3.0), (9.0, 5.0)]})


In [ ]:
data

x1   x2
0  2.0  7.0
1  3.0  6.0
2  5.0  5.0
3  7.0  4.0
4  8.0  3.0
5  9.0  5.0

# SVM Calculation

In [ ]:
mat = np.array([ [36,35,41] , [35,34,40] , [41,40,54] ])
inv = np.linalg.inv(mat)
const = np.array([-1,-1,1])
mat, inv, const

(array([[36, 35, 41],
        [35, 34, 40],
        [41, 40, 54]]), array([[-29.5  ,  31.25 ,  -0.75 ],
        [ 31.25 , -32.875,   0.625],
        [ -0.75 ,   0.625,   0.125]]), array([-1, -1,  1]))

In [ ]:
ans = np.dot(const, inv)
ans

array([-2.5 ,  2.25,  0.25])

In [ ]:
def EuclideanDistance(row, point):
  distance = 0.0
  for i in range(len(point)):
    distance += (row[i] - point[i]) ** 2
  return distance**0.5

In [ ]:
x = [(1,2), (2,3), (3,4)]
y = [(2,2), (2,1), (3,5)]
distances = []
for point in x:
  distance = []
  for row in y:
    distance.append(EuclideanDistance(row,point))
  distances.append(distance)
distances

[[1.0, 1.4142135623730951, 3.605551275463989],
 [1.0, 2.0, 2.23606797749979],
 [2.23606797749979, 3.1622776601683795, 1.0]]

In [ ]:
import numpy as np
s1 = np.array([6.9, 3.1, 4.9, 1.5, 1])
s2 = np.array([6.3,2.9, 5.6, 1.8, 1])

In [ ]:
z11 = np.dot(s1,s1.T) + 1
z21 = np.dot(s2,s1.T) + 1
z12 = np.dot(s1,s2.T) + 1
z22 = np.dot(s2,s2.T) + 1
z11, z21, z12, z22

(85.48, 84.60000000000001, 84.60000000000001, 84.69999999999999)

In [ ]:
952.24*s1-953.26*s2

array([ 564.918,  187.49 , -672.28 , -287.508,   -1.02 ])

In [ ]:
np.tanh(85.48)

1.0

In [ ]:
def sigmoid(z):
  return 1. / (1. + np.exp(-z))


In [ ]:
sigmoid(z11/100), sigmoid(z12/100), sigmoid(z21/100), sigmoid(z22/100)

(0.7015730816450415,
 0.6997273785920499,
 0.6997273785920499,
 0.6999374455926537)